saturday_review/apps/appointments/urls.py
from django.conf.urls import url

from views import *

urlpatterns = [
    url(r'^$', index, name='app_home'),
]

saturday_review/apps/employees/urls.py
from django.conf.urls import url
from views import *
# from django.contrib import admin

urlpatterns = [
    url(r'^$', employees, name='emp_home'),
]

saturday_review/apps/login/urls.py
from django.conf.urls import url

from views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register$', register_method, name='register_subroute'),
    url(r'^login$', login_method, name='login_method'),
    url(r'^logout$', logout, name='logout')
]

saturday_review/saturday_review/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^login/', include('apps.login.urls', namespace='login')),
    url(r'^employees/', include('apps.employees.urls', namespace='employees')),
    url(r'^', include('apps.appointments.urls', namespace='appointments')),
]

saturday_review/apps/appointments/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

saturday_review/apps/employees/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

saturday_review/apps/login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

saturday_review/apps/appointments/views.py
from django.shortcuts import render, HttpResponse, redirect

def index(request):
    if 'username' in request.session:
        return render(request, 'login/appt.html')
    else:
        return redirect('login:index')

saturday_review/apps/employees/views.py
from django.shortcuts import render, redirect, HttpResponse

def employees(request):

    if 'username' not in request.session:
        return redirect('login:index')
    else:
        return HttpResponse('This is the employees app')

saturday_review/apps/login/views.py
from django.shortcuts import render, HttpResponse, redirect

def index(request):
    if 'employee' in request.session:
        return redirect('employees:emp_home')
    if 'appointment' in request.session:
        return redirect('appointments:app_home')
    return render(request, 'login/index.html')

def register_method(request):
    error = is_valid(request.POST['username'], request.POST['password'], request.POST['confirm'])
    if len(error) == 0:
        return redirect('employees:emp_home')
    else:
        return redirect('login:index')


def login_method(request):
    request.session['appointment'] = True
    request.session['username'] = request.POST['username']
    error = []

    check = True

    if len(request.POST['username']) == 0:
        check = False
        messages.add_message(request, messages.ERROR, 'username cannot be blank')

    if len(request.POST['password']) < 8:
        check = False
        messages.add_message(request, messages.ERROR, 'Password cannot be less than 8 characters long')

    if request.POST['password'] != request.POST['confirm']:
        messages.add_message(request, messages.ERROR, 'invalid password')
        check = False

    if check == True:
        return redirect('appointments:app_home')

def logout(request):
    request.session.clear()
    return redirect('login:index')

def is_valid(username, password, confirm):

    error = []

    if len(username) == 0:
        error.append('username cannot be blank')

    if len(password) < 8:
        error.append('password cannot be less than 8 characters')

    if password != confirm:
        error.append('invalid password')

    return error

saturday_review/apps/login/templates/login/appt.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Appointment Page</title>
  </head>
  <body>
      <a href="{% url 'login:logout' %}"><button type="button">Logout</button></a>
  </body>
</html>

saturday_review/apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Login and Registration</title>
    </head>
    <body>
        <h1>Register</h1>
        <form action="{% url 'login:register_subroute'%}" method="POST">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" value="ryan">
            <label for="password">Password</label>
            <input type="password" name="password" value="not_secure_password">
            <label for="confirm">Confirm Password</label>
            <input type="password" name="confirm" value="not_secure_confirmation">
            <input type="submit">
        </form>

        <h1>Login</h1>
        <form action="{% url 'login:login_method'%}" method="POST">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" value="">
            <label for="password">Password</label>
            <input type="password" name="password" value="">
            <input type="submit">

            {% for messages in messages %}
            {{messages}}
            {%endfor%}
        </form>
    </body>
</html>