surveypractice/apps/surveyapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^result$', process, name='process')
]

surveypractice/surveypractice/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.surveyapp.urls', namespace='surveyapp')),
]

surveypractice/apps/surveyapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

surveypractice/apps/surveyapp/views.py
from django.shortcuts import render

def index(request):
    request.session['counter'] = 0

    return render(request, 'index.html')

def process(request):
    request.session['name'] = request.POST['name']
    request.session['location'] = request.POST['location']
    request.session['language'] = request.POST['language']
    request.session['comment'] = request.POST['comment']

    if 'counter' in request.session:
        request.session['counter'] += 1

    return render(request, 'results.html')

surveypractice/apps/surveyapp/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Survey Form</title>
  </head>
  <body>

    <form action="{% url 'surveyapp:process'%}" method="POST">
      {% csrf_token %}
      <p>Your Name: </p><input type="text" name="name">
      <p>Dojo Location: </p>
      <select name = 'location'>
        <option value="Mountain View">Mountain View</option>
        <option value="Chicago">Chicago</option>
        <option value="California">California</option>
      </select>
      <br>
      <select name="language">
        <option value="Python">Python</option>
        <option value="HTML">HTML</option>
        <option value="JavaScript">JavaScript</option>
      </select>
        <h4>Comment: </h4>
        <textarea name="comment" rows="8" cols="80"></textarea>
        <input type="submit" name="submit">
    </form>

  </body>
</html>

surveypractice/apps/surveyapp/templates/results.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Results</title>
  </head>
  <body>

    <h4>Thanks for submitting this form! You have submitted this form {{request.session.counter}} times now</h4>

    <h4>Submitted Information</h4>

    <p>Name: {{request.session.name}}</p>
    <p>Dojo Location: {{request.session.location}}</p>
    <p>Favorite Language: {{request.session.language}}</p>
    <p>Comment: {{request.session.comment}}</p> 
  </body>
</html>