beginner_project/apps/login/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login$', authenticate, name='authenticate'),
    url(r'^register$', register, name='register'),
    url(r'^success$', success, name='success'),
]

beginner_project/beginner_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^login/', include('apps.login.urls', namespace='login')),
    url(r'^admin/', admin.site.urls),
]

beginner_project/apps/login/models.py
from __future__ import unicode_literals
import re
import bcrypt

from django.db import models
from django.db import IntegrityError


REGEX_EMAIL = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
REGEX_PASSWORD  = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$')

class UserManager(models.Manager):
    def validate_user(self, username, email, password, confirm):
        errors = []
        if len(username) < 3:
            errors.append('username too short')
        if REGEX_EMAIL.search(email) is None:
            errors.append('invalid email')
        if REGEX_PASSWORD.search(password) is None:
            errors.append('password too weak')
        if password != confirm:
            errors.append('passwords do not match')
        return errors

    def create_user(self, username, email, password):
        errors = []
        try:
            hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
            User.objects.create(username=username, email=email, password=hashed)
        except IntegrityError:
            errors.append('user already exists')
        except IndexError:
            errors.append('you suck')

        return errors

    def authenticate_user(self, username, password):
        try:
            user = User.objects.get(username=username)
            return bcrypt.hashpw(password.encode(), user.password.encode()) == user.password
        except:
            return False

class User(models.Model):
    username = models.CharField(max_length=64, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

beginner_project/apps/management/models.py
from __future__ import unicode_literals

from django.db import models
from ..login.models import *

class Team(models.Model):
    manager = models.ForeignKey(User, related_name='manager_of')
    employeee = models.ForeignKey(User)

beginner_project/apps/login/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages

from models import *

def index(request):
    return render(request, 'login/index.html')

def register(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    confirm = request.POST['confirm']

    errors = []
    errors += User.objects.validate_user(username, email, password, confirm)
    
    if len(errors) == 0:
        errors = User.objects.create_user(username, email, password)
        if len(errors) == 0:
            return redirect('login:success')
    
    for e in errors:
        messages.add_message(request, messages.ERROR, e)
        
    # experiment with reverse 'lookup'
    return redirect('login:index')

def success(request):
    return HttpResponse("SUCCESSFULLY CREATED USER")

def authenticate(request):
    username = request.POST['username']
    password = request.POST['password']
    if User.objects.authenticate_user(username, password):
        # give the proper redirect
        return redirect('login:success')
    else:
        messages.add_message(request, messages.ERROR, 'invalid login')
        return redirect('login:index')

beginner_project/apps/management/views.py
from django.shortcuts import render

# Create your views here.

beginner_project/apps/login/templates/login/index.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
    </head>
    <body>
        <div>
            {% for m in messages %}
                <div>{{m}}</div>
            {% endfor %}
        </div>
        <div>
            <form action="{% url 'login:authenticate' %}" method="POST">
                {% csrf_token %}
                <label for="username">User Name</label>
                <input type="text" name="username" value="">
                <label for="password">Password</label>
                <input type="password" name="password" value="">
                <input type="submit" value="Login">
            </form>
        </div>

        <div>
            <form action="{% url 'login:register' %}" method="POST">
                {% csrf_token %}
                <label for="username">User Name</label>
                <input type="text" name="username" value="">
                <label for="email">Email Address</label>
                <input type="text" name="email" value="">
                <label for="password">Password</label>
                <input type="password" name="password" value="">
                <label for="confirm">Confirm Password</label>
                <input type="password" name="confirm" value="">
                <input type="submit" value="Register">
            </form>
        </div>

    </body>
</html>